Bump decidim
OpenSourcePolitics/decidim-lyon pull request #20
Opened 2022-09-22 14:56 UTC by armandfardeau

2022-09-23 16:16 UTC, moustachu approved these changes

2022-09-26 16:39 UTC, paulinebessoles approved these changes

2022-10-03 09:50 UTC, Quentinchampenois requested changes
Just a simple log to remove otherwise it is all good to me  !

2022-10-03 09:50 UTC, Quentinchampenois commented on app/packs/src/decidim/proposals/add_proposal.js
> +console.log("coucou")
Does this log work as expected ? 😄

2022-10-03 09:52 UTC, armandfardeau commented on app/packs/src/decidim/proposals/add_proposal.js
> +console.log("coucou")
ROFL, I forgot this one

2022-10-03 10:27 UTC, merged