Upgrade to 0.26.5
OpenSourcePolitics/decidim-lyon pull request #38
Opened 2023-02-09 17:38 UTC by paulinebessoles

2023-02-22 14:30 UTC, armandfardeau approved these changes

2023-02-27 15:23 UTC, armandfardeau requested changes
Hello, could you fix conflicts please?

2023-02-27 16:12 UTC, paulinebessoles commented
@armandfardeau it should be okay now!

2023-02-27 18:24 UTC, armandfardeau approved these changes

2023-03-03 07:53 UTC, merged