Chores/backport k8s
OpenSourcePolitics/decidim-lyon pull request #44
Opened 2023-07-21 16:14 UTC by armandfardeau

#### :tophat: Description
*Please describe your pull request.*

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #?
- Fixes #?
- [Notion card]()

#### Testing
*Describe the best way to test or validate your PR.*

Example:
* Log in as admin
* Access Backoffice
* Go to organization settings
* See ...

#### Tasks
- [ ] Add specs
- [ ] Add note about overrides in OVERLOADS.md

### :camera: Screenshots
*Please add screenshots of the changes you're proposing if related to the UI*

2023-07-25 13:55 UTC, AyakorK approved these changes

2023-07-26 07:30 UTC, Quentinchampenois reviewed
Some english locales are translated in french in `config/locales/en.yml`

2023-07-26 10:19 UTC, paulinebessoles requested changes
I encounter an issue when trying to vote for a project on a budget component. 

<img width="584" alt="Capture d’écran 2023-07-26 à 12 18 15" src="https://github.com/OpenSourcePolitics/decidim-lyon/assets/52420208/6b8618a2-33e0-4560-a2b7-f1bb7a510130">

2023-09-07 08:40 UTC, paulinebessoles approved these changes

2023-09-07 08:56 UTC, merged